// Path: backend/wallet-service/src/Constraints/ProductList.js

// const PRODUCT_LIST = [
//   {
//     name: "Coconut and Aloe Vera Hair Oil",
//     benefits: "Nourishes and protects the hair, promoting healthy growth and shine.",
//     productCode: 2065,
//     mrp: 350,
//     dp: 280,
//   },
//   {
//     name: "Onion and Black Seed Shampoo",
//     benefits: "May be beneficial for hair growth, scalp health, and hair nourishment. Consistent use is key.",
//     productCode: 1145,
//     mrp: 400,
//     dp: 300,
//   },
//   {
//     name: "Multifruits Face Wash",
//     benefits: "Cleanses and nourishes your skin while enjoying the benefits of various fruits.",
//     productCode: 2103,
//     mrp: 250,
//     dp: 160,
//   },
//   {
//     name: "Mixed Multi-Berry Capsules",
//     benefits: "Supports overall health and well-being. Consult a healthcare professional before use.",
//     healthBenefits: [
//       "Skin Health",
//       "Digestive Health",
//       "Antibacterial Properties",
//       "Diabetes Management",
//       "Oral Health",
//       "Reproductive Health",
//       "Anti-Inflammatory Agent",
//       "Detoxification",
//       "Immune System Boost",
//     ],
//     productCode: 8014,
//     mrp: 700,
//     dp: 520,
//   },
//   {
//     name: "Aloe Vera Capsules",
//     benefits: "Great addition to a healthy lifestyle, providing various benefits for overall health and well-being.",
//     productCode: 1025,
//     mrp: 500,
//     dp: 500,
//   },
//   {
//     name: "Aloe Vera Capsules",
//     benefits: "Provides numerous benefits for overall health and well-being.",
//     productCode: 1001,
//     mrp: 500,
//     dp: 350,
//   },
// ];
const PRODUCT_LIST = [
    {
    productCode: 5025,
    name: 'Silver Package',
    dp: 1000,
    mrp: 1200,
    image: '/assets/images/Silver_2.jpg',
  },  {
    productCode: 5026,
    name: 'Golden Package',
    dp: 5000,
    mrp: 6000,
    image: '/assets/images/golden_2.jpg',
  },  {
    productCode: 5027,
    name: 'Diamond Package',
    dp: 10000,
    mrp: 12000,
    image: '/assets/images/diamond_2.jpg',
  },
  {
   
    productCode: 1025,
    name: 'Neem Extract',
    dp: 350,
    mrp: 500,
    image: '/assets/images/i1.png',
  },
  {
    id: 2,
    productCode: 8014,
    name: 'Mix Multi Berries Capsules',
    dp: 520,
    mrp: 700,
    image: '/assets/images/i2.png',
  },
  {
    id: 3,
    productCode: 1103,
    name: 'Golden Package',
    dp: 1049,
    mrp: 2049,
    image: '/assets/images/combo.png',
  },
  {
    id: 4,
    productCode: 2065,
    name: 'Silver Package',
    dp: 549,
    mrp: 1049,
    image: '/assets/images/silver.png',
  },
  {
    id: 5,
    productCode: 1145,
    name: 'Gift Box',
    dp: 100,
    mrp: 200,
    image: '/assets/images/gift.jpg',
  },
  {
    id: 6,
    productCode: 1001,
    name: 'Aloe-Vera Extract',
    dp: 350,
    mrp: 500,
    image: '/assets/images/i6.jpg',
  },
  {
    productCode: 1050,
    name: 'Softcare Sanitary Pad (30 Pcs) ',
    dp: 525,
    mrp: 900,
    image: '/assets/images/i7.jpg',
  },
  {
    productCode: 1055,
    name: 'Alkaline water bottle',
    dp: 3199,
    mrp: 5199,
    image: '/assets/images/i8.jpg',
  },
  {
    productCode: 1065,
    name: 'Combo of 7',
    dp: 5199,
    mrp: 8599,
    image: '/assets/images/i9.jpg',
  },
];

module.exports = PRODUCT_LIST;

